### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by sanzeeb3** [RatulHasan/my-github#1]
This line results in a syntax error.

https://github.com/RatulHasan/my-github/blob/3112d9710ad939ae023fd6f00a54180d12d395a6/includes/Admin/Settings.php#L28

>  PHP Parse error:  syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const

**Comment by RatulHasan** [comment]
My $sections variable accepts only array type. if you store string type in
this variable it will cause error.

*Best Regards,*
*M.M. Tanjil Hasan Ratul*
Software Engineer
BeSofty Software Ltd.
17/3 , Mirpur Road | Dhaka-1205
*Work:* +8801915170777
*website* : www.besofty.com <http://besofty.com/>

**Comment by RatulHasan** [comment]
My $sections variable accepts only array type. if you want to store string type in this variable it will cause error.

**Comment by sanzeeb3** [comment]
That's an incorrect syntax. Upgrade you php.

**Comment by RatulHasan** [comment]
Thanks for your co-operation. It's now updated.
