### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by bertholdm** [RatulHasan/my-github#3]
After installing, activate and customizing the plugin and embedding [my_github] in a new page, the message 
**Failed to load plugin url: https://(my site)/wp-content/plugins/my-github/assets/my_github_qtags.js**
appears and no content from GitHub is shown..

Environment:
WordPress 5.7.2
Classic editor

Thanks!

**Comment by RatulHasan** [comment]
Hey, Thanks for your valuable findings. Issue fixed. Please re-install the plugin.

**Comment by bertholdm** [comment]
Great! It works now and looks good.

Thanks again!

Am Di., 18. Mai 2021 um 20:33 Uhr schrieb Ratul Hasan <
***@***.***>:
